version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      POSTGRES_DB: stock_trading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - .env

  flower:
    build: .
    command: celery -A core flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db
    environment:
      - .env